# Generated by Django 4.0.5 on 2022-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
